# Auto-generated country mapping
# Generated by discover_countries.py
# Range: 5 to 7

COUNTRY_NAMES = {
    "50": "Naha",  # 20 attractions
    "503": "Gangtok",  # 20 attractions
    "51": "Phuket Town",  # 20 attractions
    "518": "Visakhapatnam",  # 20 attractions
    "52": "Yangon (Rangoon)",  # 20 attractions
    "524": "Guwahati",  # 20 attractions
    "527": "Kozhikode",  # 20 attractions
    "528": "Singaraja",  # 20 attractions
    "53": "Kathu",  # 20 attractions
    "536": "Thrissur",  # 20 attractions
    "541": "Thane",  # 20 attractions
    "558": "Indore",  # 20 attractions
    "563": "Noida",  # 20 attractions
    "57": "Pune",  # 20 attractions
    "570": "Batu",  # 20 attractions
    "57258": "Dublin",  # 20 attractions
    "58044": "Vancouver Island",  # 20 attractions
    "58045": "Toronto",  # 20 attractions
    "58046": "Montreal",  # 20 attractions
    "58047": "Vancouver",  # 20 attractions
    "58048": "Calgary",  # 20 attractions
    "58049": "Ottawa",  # 20 attractions
    "58050": "Victoria",  # 20 attractions
    "58051": "Quebec City",  # 20 attractions
    "58052": "Edmonton",  # 20 attractions
    "58058": "Niagara Falls",  # 20 attractions
    "58059": "Halifax",  # 20 attractions
    "58067": "Kingston",  # 20 attractions
    "58068": "Banff",  # 20 attractions
    "58077": "Tofino",  # 20 attractions
    "58079": "North Vancouver",  # 20 attractions
    "581": "Calangute",  # 20 attractions
    "58144": "New York City",  # 20 attractions
    "58145": "Los Angeles",  # 20 attractions
    "58146": "Chicago",  # 20 attractions
    "58147": "San Francisco",  # 20 attractions
    "58148": "Las Vegas",  # 20 attractions
    "58150": "San Diego",  # 20 attractions
    "58151": "Maui",  # 20 attractions
    "58152": "Orlando",  # 20 attractions
    "58153": "Honolulu",  # 30 attractions
    "58154": "Seattle",  # 20 attractions
    "58155": "Island of Hawaii",  # 20 attractions
    "58156": "New Orleans",  # 20 attractions
    "58157": "Miami",  # 20 attractions
    "58158": "Portland",  # 20 attractions
    "58159": "Washington DC",  # 20 attractions
    "58160": "Philadelphia",  # 20 attractions
    "58161": "Houston",  # 20 attractions
    "58162": "Boston",  # 20 attractions
    "58163": "Austin",  # 20 attractions
    "58164": "Brooklyn",  # 20 attractions
    "58165": "Key West",  # 20 attractions
    "58166": "Denver",  # 20 attractions
    "58167": "Kauai",  # 20 attractions
    "58168": "San Antonio",  # 20 attractions
    "58169": "Atlanta",  # 40 attractions
    "58170": "Charleston",  # 20 attractions
    "58171": "Nashville",  # 20 attractions
    "58172": "Tucson",  # 20 attractions
    "58173": "Dallas",  # 20 attractions
    "58174": "Savannah",  # 20 attractions
    "58175": "Saint Louis",  # 20 attractions
    "58176": "Tampa",  # 20 attractions
    "58177": "Fort Lauderdale",  # 20 attractions
    "58178": "Santa Fe",  # 20 attractions
    "58179": "Baltimore",  # 20 attractions
    "58180": "Miami Beach",  # 20 attractions
    "58181": "Phoenix",  # 20 attractions
    "58182": "Greater Palm Springs",  # 20 attractions
    "58183": "Branson",  # 20 attractions
    "58184": "Minneapolis",  # 20 attractions
    "58185": "Asheville",  # 20 attractions
    "58187": "Sarasota",  # 20 attractions
    "58188": "Sedona",  # 20 attractions
    "58189": "Naples",  # 20 attractions
    "58191": "Albuquerque",  # 20 attractions
    "58192": "Scottsdale",  # 20 attractions
    "58193": "Charlotte",  # 20 attractions
    "58195": "Milwaukee",  # 9 attractions
    "58196": "Louisville",  # 20 attractions
    "58198": "Anchorage",  # 20 attractions
    "58199": "Pittsburgh",  # 20 attractions
    "58201": "Cincinnati",  # 20 attractions
    "58202": "Myrtle Beach",  # 20 attractions
    "58203": "Lahaina",  # 20 attractions
    "58205": "Indianapolis",  # 20 attractions
    "58206": "Santa Barbara",  # 20 attractions
    "58210": "Cleveland",  # 20 attractions
    "58211": "Fort Myers",  # 20 attractions
    "58212": "Fort Worth",  # 20 attractions
    "58213": "Omaha",  # 20 attractions
    "58216": "Salt Lake City",  # 20 attractions
    "58218": "Detroit",  # 20 attractions
    "58219": "Kansas City",  # 20 attractions
    "58222": "Richmond",  # 20 attractions
    "58224": "Memphis",  # 20 attractions
    "58226": "Chattanooga",  # 20 attractions
    "58228": "Santa Monica",  # 20 attractions
    "58231": "Clearwater",  # 20 attractions
    "58232": "Oklahoma City",  # 20 attractions
    "58241": "Pigeon Forge",  # 20 attractions
    "58242": "Anaheim",  # 20 attractions
    "58244": "Galveston",  # 20 attractions
    "58248": "Daytona Beach",  # 20 attractions
    "58269": "Moab",  # 20 attractions
    "58275": "Williamsburg",  # 20 attractions
    "58276": "Monterey",  # 20 attractions
    "58284": "Fredericksburg",  # 20 attractions
    "58286": "Gettysburg",  # 20 attractions
    "58289": "Salem",  # 20 attractions
    "583": "Solo",  # 20 attractions
    "58300": "Flagstaff",  # 20 attractions
    "58342": "Arlington",  # 20 attractions
    "58345": "Wisconsin Dells",  # 20 attractions
    "584": "Kanchanaburi",  # 20 attractions
    "58455": "Athens",  # 20 attractions
    "58476": "Page",  # 20 attractions
    "58563": "Columbus",  # 20 attractions
    "58748": "Titusville",  # 20 attractions
    "589": "Port Blair",  # 20 attractions
    "59": "Hiroshima",  # 20 attractions
    "59165": "Keystone",  # 20 attractions
    "6": "Beijing",  # 20 attractions
    "60": "Agra",  # 20 attractions
    "607": "Aurangabad",  # 20 attractions
    "61": "Busan",  # 20 attractions
    "615": "Madurai",  # 20 attractions
    "62": "Kanazawa",  # 20 attractions
    "64": "Hangzhou",  # 19 attractions
    "650": "Sentosa Island",  # 20 attractions
    "660": "Ella",  # 20 attractions
    "662": "Varkala Town",  # 20 attractions
    "67": "Chengdu",  # 20 attractions
    "673": "Patna",  # 20 attractions
    "68": "Kochi (Cochin)",  # 20 attractions
    "687": "Mussoorie",  # 20 attractions
    "69": "Kolkata (Calcutta)",  # 20 attractions
    "696": "Hampi",  # 20 attractions
}
