# Auto-generated country mapping
# Generated by discover_countries.py
# Range: 15794 to 3

COUNTRY_NAMES = {
    "16": "Ho Chi Minh City",  # 19 attractions
    "161": "Ahmedabad",  # 20 attractions
    "1659": "Vasco da Gama",  # 13 attractions
    "1668": "Hassan",  # 15 attractions
    "1699": "Margao",  # 20 attractions
    "17": "Kathmandu",  # 20 attractions
    "1729": "Gaya",  # 20 attractions
    "174": "Da Lat",  # 20 attractions
    "1743": "Diu",  # 20 attractions
    "175": "Manila",  # 34 attractions
    "176": "Karon",  # 20 attractions
    "1763": "Jamshedpur",  # 20 attractions
    "1765": "Almora",  # 20 attractions
    "1784": "Dalhousie",  # 20 attractions
    "18": "Taipei",  # 20 attractions
    "1808": "Daman",  # 20 attractions
    "183": "Jaisalmer",  # 20 attractions
    "184": "Luang Prabang",  # 20 attractions
    "1868": "Baga",  # 20 attractions
    "187": "Melaka",  # 20 attractions
    "1874": "Vrindavan",  # 20 attractions
    "1886": "Madikeri",  # 20 attractions
    "1887": "Coonoor",  # 20 attractions
    "19": "Chiang Mai",  # 20 attractions
    "194": "Rishikesh",  # 20 attractions
    "1942": "Shimoga",  # 20 attractions
    "1966": "Kovalam",  # 20 attractions
    "1983": "Dwarka",  # 20 attractions
    "1997": "Tiruvannamalai",  # 15 attractions
    "2": "Kyoto",  # 20 attractions
    "20": "Yokohama",  # 20 attractions
    "200": "Thiruvananthapuram (Trivandrum)",  # 20 attractions
    "2027": "Orchha",  # 20 attractions
    "207": "Gurugram (Gurgaon)",  # 20 attractions
    "2083": "Howrah",  # 20 attractions
    "209": "Thimphu",  # 20 attractions
    "21": "Hoi An",  # 20 attractions
    "2121": "Deoghar",  # 20 attractions
    "2141": "Kohima",  # 20 attractions
    "2177": "Gandhinagar",  # 20 attractions
    "22": "Ubud",  # 20 attractions
    "221": "Sapa",  # 20 attractions
    "223": "Kuching",  # 19 attractions
    "2253": "Pahalgam",  # 20 attractions
    "228": "Beppu",  # 20 attractions
    "23": "Minato",  # 20 attractions
    "235": "Lahore",  # 20 attractions
    "2371": "Gokarna",  # 20 attractions
    "24": "Jaipur",  # 20 attractions
    "247": "Ise",  # 20 attractions
    "248": "Lhasa",  # 17 attractions
    "25": "Mumbai",  # 20 attractions
    "2540": "Kumarakom",  # 20 attractions
    "256": "Srinagar",  # 20 attractions
    "257": "Chiang Rai",  # 20 attractions
    "2601": "Amphawa",  # 14 attractions
    "28": "Taito",  # 20 attractions
    "283": "Dhaka City",  # 20 attractions
    "285": "Seogwipo",  # 20 attractions
    "287": "Panjim",  # 20 attractions
    "288": "Karachi",  # 20 attractions
    "29": "Sapporo",  # 20 attractions
    "297": "Leh",  # 20 attractions
}
