# Auto-generated country mapping
# Generated by discover_countries.py
# Range: 3 to 5

COUNTRY_NAMES = {
    "30": "Nagoya",  # 20 attractions
    "304": "Chandigarh",  # 20 attractions
    "31": "Fukuoka",  # 20 attractions
    "3129": "Digha",  # 20 attractions
    "313": "Manali Tehsil",  # 14 attractions
    "32": "Shinjuku",  # 20 attractions
    "329": "Bardez",  # 20 attractions
    "33": "Kuala Lumpur",  # 20 attractions
    "330": "Tashkent",  # 18 attractions
    "334": "Pondicherry",  # 20 attractions
    "34": "Kobe",  # 20 attractions
    "348": "Vadodara",  # 20 attractions
    "349": "Darjeeling",  # 20 attractions
    "35": "Bengaluru",  # 20 attractions
    "350": "Alappuzha",  # 20 attractions
    "37": "Kuta",  # 20 attractions
    "371": "Coimbatore",  # 20 attractions
    "375": "Lucknow",  # 20 attractions
    "376": "Ipoh",  # 20 attractions
    "38": "Shibuya",  # 20 attractions
    "381": "Semarang",  # 20 attractions
    "382": "Medan",  # 20 attractions
    "384": "Amritsar",  # 20 attractions
    "39": "Guangzhou",  # 20 attractions
    "398": "Nagpur",  # 20 attractions
    "4": "Bangkok",  # 20 attractions
    "405": "Dharamsala",  # 20 attractions
    "41": "New Taipei",  # 20 attractions
    "412": "Munnar",  # 20 attractions
    "419": "Hikkaduwa",  # 17 attractions
    "42": "Chiyoda",  # 20 attractions
    "428": "Shimla",  # 20 attractions
    "43": "Colombo",  # 20 attractions
    "44": "Phnom Penh",  # 20 attractions
    "444": "Bhubaneswar",  # 20 attractions
    "449": "Nashik",  # 20 attractions
    "46": "Jakarta",  # 20 attractions
    "461": "Kannur",  # 20 attractions
    "465": "Gyeongju",  # 20 attractions
    "468": "Ayutthaya",  # 20 attractions
    "472": "Navi Mumbai",  # 20 attractions
    "478": "Surat",  # 20 attractions
    "479": "Mangalore",  # 20 attractions
    "480": "Ooty (Udhagamandalam)",  # 7 attractions
    "485": "Bhopal",  # 20 attractions
    "49": "Da Nang",  # 20 attractions
}
