# Auto-generated country mapping
# Generated by discover_countries.py
# Range: 8 to 9

COUNTRY_NAMES = {
    "80": "Pattaya",  # 20 attractions
    "805": "Tiruchirappalli",  # 20 attractions
    "81180": "Punta Cana",  # 20 attractions
    "81182": "Havana",  # 19 attractions
    "81187": "Grand Cayman",  # 20 attractions
    "81189": "San Juan",  # 20 attractions
    "81190": "New Providence Island",  # 20 attractions
    "81194": "Nassau",  # 20 attractions
    "81196": "Willemstad",  # 20 attractions
    "81197": "Santo Domingo",  # 20 attractions
    "81213": "Ocho Rios",  # 20 attractions
    "81219": "Puerto Plata",  # 20 attractions
    "81226": "Varadero",  # 20 attractions
    "81250": "Santiago de Cuba",  # 19 attractions
    "814": "Canacona",  # 20 attractions
    "81903": "Mexico City",  # 20 attractions
    "81904": "Cancun",  # 20 attractions
    "81905": "Playa del Carmen",  # 20 attractions
    "81906": "Puerto Vallarta",  # 20 attractions
    "81908": "Cozumel",  # 20 attractions
    "81909": "Tulum",  # 20 attractions
    "81911": "Oaxaca",  # 20 attractions
    "81912": "Guadalajara",  # 20 attractions
    "81913": "Merida",  # 20 attractions
    "81918": "Puebla",  # 20 attractions
    "81924": "Guanajuato",  # 20 attractions
    "81941": "Akumal",  # 20 attractions
    "81981": "Palenque",  # 17 attractions
    "82": "Baku",  # 31 attractions
    "82574": "Sydney",  # 20 attractions
    "82575": "Melbourne",  # 20 attractions
    "82576": "Auckland",  # 20 attractions
    "82577": "Brisbane",  # 20 attractions
    "82578": "Gold Coast",  # 20 attractions
    "82579": "Christchurch",  # 20 attractions
    "82581": "Adelaide",  # 20 attractions
    "82582": "Wellington",  # 20 attractions
    "82584": "Cairns",  # 20 attractions
    "82585": "Canberra",  # 20 attractions
    "82586": "Hobart",  # 34 attractions
    "82588": "Darwin",  # 20 attractions
    "82593": "Rotorua",  # 20 attractions
    "82594": "Dunedin",  # 20 attractions
    "82608": "Newcastle",  # 20 attractions
    "82614": "Broome",  # 20 attractions
    "82615": "Taupo",  # 20 attractions
    "827": "Tirunelveli",  # 20 attractions
    "842": "Kodaikanal",  # 20 attractions
    "849": "Kottayam",  # 20 attractions
    "85": "Suzhou",  # 20 attractions
    "850": "Khajuraho",  # 20 attractions
    "85939": "Dubai",  # 20 attractions
    "85940": "Tel Aviv",  # 20 attractions
    "85941": "Jerusalem",  # 20 attractions
    "85942": "Abu Dhabi",  # 20 attractions
    "85943": "Tehran",  # 20 attractions
    "85946": "Doha",  # 20 attractions
    "85954": "Manama",  # 20 attractions
    "85959": "Jeddah",  # 20 attractions
    "85962": "Al Ain",  # 20 attractions
    "85998": "Mecca",  # 20 attractions
    "86647": "Japan",  # 20 attractions
    "86651": "Thailand",  # 20 attractions
    "86652": "Philippines",  # 9 attractions
    "86654": "Singapore",  # 9 attractions
    "86655": "Vietnam",  # 20 attractions
    "86656": "South Korea",  # 20 attractions
    "86659": "Cambodia",  # 20 attractions
    "86661": "India",  # 20 attractions
    "86667": "Nepal",  # 20 attractions
    "86668": "Taiwan",  # 19 attractions
    "86674": "Rajasthan",  # 17 attractions
    "86675": "Maharashtra",  # 20 attractions
    "86676": "Hokkaido",  # 20 attractions
    "86686": "Karnataka",  # 20 attractions
    "86689": "Guangdong",  # 20 attractions
    "86691": "Tamil Nadu",  # 20 attractions
    "86693": "Sri Lanka",  # 20 attractions
    "86706": "Uttar Pradesh",  # 20 attractions
    "86714": "Kerala",  # 19 attractions
    "86716": "West Bengal",  # 20 attractions
    "86722": "Jiangsu",  # 19 attractions
    "86729": "Azerbaijan",  # 20 attractions
    "86731": "Kazakhstan",  # 20 attractions
    "86743": "Fujian",  # 20 attractions
    "86772": "Mongolia",  # 20 attractions
    "86776": "Kyrgyzstan",  # 19 attractions
    "86779": "Brunei Darussalam",  # 11 attractions
    "86797": "Laos",  # 20 attractions
    "86805": "Uttarakhand",  # 20 attractions
    "86819": "Bhutan",  # 20 attractions
    "86831": "Pakistan",  # 20 attractions
    "86851": "Bangladesh",  # 20 attractions
    "86887": "Punjab",  # 20 attractions
    "86904": "Odisha",  # 20 attractions
    "86937": "Assam",  # 20 attractions
    "86938": "Tajikistan",  # 11 attractions
    "86988": "Meghalaya",  # 7 attractions
    "87077": "North Korea",  # 20 attractions
    "87236": "Arunachal Pradesh",  # 9 attractions
    "87411": "Nagaland",  # 6 attractions
    "877": "Mount Abu",  # 20 attractions
    "88352": "Italy",  # 20 attractions
    "88358": "France",  # 20 attractions
    "88359": "United Kingdom",  # 19 attractions
    "88360": "Russia",  # 19 attractions
    "88362": "Spain",  # 20 attractions
    "88366": "Czech Republic",  # 20 attractions
    "88367": "Turkiye",  # 20 attractions
    "88368": "Germany",  # 20 attractions
    "88373": "The Netherlands",  # 20 attractions
    "88375": "Greece",  # 20 attractions
    "88380": "Hungary",  # 20 attractions
    "88384": "Austria",  # 20 attractions
    "88386": "Ireland",  # 20 attractions
    "88402": "Denmark",  # 20 attractions
    "88403": "Poland",  # 20 attractions
    "88406": "Bavaria",  # 20 attractions
    "88407": "Malta",  # 20 attractions
    "88408": "Belgium",  # 19 attractions
    "88419": "Iceland",  # 20 attractions
    "88420": "Georgia",  # 20 attractions
    "88423": "Latvia",  # 20 attractions
    "88432": "Norway",  # 20 attractions
    "88434": "Finland",  # 20 attractions
    "88437": "Switzerland",  # 20 attractions
    "88438": "Croatia",  # 20 attractions
    "88445": "Sweden",  # 20 attractions
    "88449": "Bulgaria",  # 15 attractions
    "88455": "Estonia",  # 18 attractions
    "88464": "Serbia",  # 20 attractions
    "88477": "Lithuania",  # 20 attractions
    "88478": "Slovakia",  # 20 attractions
    "88486": "Slovenia",  # 20 attractions
    "88503": "Belarus",  # 20 attractions
    "88527": "Cyprus",  # 19 attractions
    "88609": "Albania",  # 20 attractions
    "88654": "Montenegro",  # 20 attractions
    "88723": "Luxembourg",  # 20 attractions
    "88731": "Moldova",  # 20 attractions
    "894": "Rajkot",  # 20 attractions
    "895": "Nainital",  # 20 attractions
}
