# Auto-generated country mapping
# Generated by discover_countries.py
# Range: 7 to 8

COUNTRY_NAMES = {
    "701": "Lonavala",  # 20 attractions
    "714": "Kollam",  # 20 attractions
    "717": "Male",  # 12 attractions
    "722": "Pushkar",  # 20 attractions
    "724": "Ninh Binh",  # 13 attractions
    "728": "Shillong",  # 20 attractions
    "73": "Yerevan",  # 20 attractions
    "730": "Jamnagar",  # 20 attractions
    "738": "Thanjavur",  # 20 attractions
    "74": "Xi'an",  # 20 attractions
    "75": "Nagasaki",  # 20 attractions
    "753": "Thekkady",  # 20 attractions
    "76078": "Lake Louise",  # 20 attractions
    "78": "Hyderabad",  # 20 attractions
    "783": "Haridwar",  # 20 attractions
    "785": "Allahabad",  # 20 attractions
    "787": "Chikmagalur",  # 20 attractions
    "78744": "Panama City",  # 20 attractions
    "78746": "San Jose",  # 20 attractions
    "78752": "La Fortuna de San Carlos",  # 20 attractions
    "79": "Krabi Town",  # 20 attractions
    "79299": "Marrakech",  # 20 attractions
    "79300": "Cape Town Central",  # 21 attractions
    "79302": "Cairo",  # 19 attractions
    "79303": "Nairobi",  # 20 attractions
    "79304": "Mauritius",  # 20 attractions
    "79305": "Fes",  # 20 attractions
    "79306": "Johannesburg",  # 20 attractions
    "79309": "Sharm El Sheikh",  # 20 attractions
    "79321": "Giza",  # 20 attractions
    "79333": "Dahab",  # 20 attractions
    "79337": "Alexandria",  # 20 attractions
    "798": "Raipur",  # 20 attractions
}
