#!/usr/bin/env python3
"""
generate_and_store_top_things_to_do.py
───────────────────────────────────────

For each (doc_id, label, locationContext) in DESTINATIONS:
 1) Generate a “top_things_to_do” JSON via OpenAI with exactly:
      • "Introduction": a 2–3 sentence opening paragraph
      • 10 keys, each beginning with a suitable emoji + title, value = a 2–3 sentence tip
      • "Conclusion": a 1–2 sentence wrap-up
 2) Store that JSON under travelInfo/top_things_to_do for each allplaces/{doc_id}.
"""

import os
import json
from json.decoder import JSONDecodeError

from openai import OpenAI
import firebase_admin
from firebase_admin import credentials, firestore

# ─── CONFIG ───────────────────────────────────────────────────────────────────
# (doc_id, short_label, full_location_context)
DESTINATIONS = [
    # ("909", "Agartala", "Agartala, Tripura, India"),
    # ("58144", "New York City", "New York City, New York, USA"),
    # ("9613", "London", "London, England, UK"),
    # ("9614", "Paris", "Paris, France"),
    # ("9616", "Rome", "Rome, Italy"),
    # ("9617", "Barcelona", "Barcelona, Spain"),
    # ("58152", "Orlando", "Orlando, Florida, USA"),
    # ("9625", "Amsterdam", "Amsterdam, Netherlands"),
    # ("9621", "Madrid", "Madrid, Spain"),
    # ("131072", "Rio de Janeiro", "Rio de Janeiro, Brazil"),
    # ("58148", "Las Vegas", "Las Vegas, Nevada, USA"),
    # ("7", "Singapore", "Singapore, Singapore"),
    # ("9623", "Berlin", "Berlin, Germany"),
    # ("4", "Bangkok", "Bangkok, Thailand"),
    # ("9620", "Prague", "Prague, Czech Republic"),
    # ("9626", "Lisbon", "Lisbon, Portugal"),
    # ("131071", "Buenos Aires", "Buenos Aires, Argentina"),
    # ("58147", "San Francisco", "San Francisco, California, USA"),
    # ("9622", "Istanbul", "Istanbul, Turkey"),
    # ("131073", "Sao Paulo", "Sao Paulo, Brazil"),
    # ("9629", "Budapest", "Budapest, Hungary"),
    # ("57258", "Dublin", "Dublin, Ireland"),
    # ("9633", "Dublin", "Dublin, Ireland"),
    # ("58159", "Washington DC", "Washington DC, USA"),
    # ("9631", "Vienna", "Vienna, Austria"),
    # ("9634", "Venice", "Venice, Italy"),
    # ("9624", "Milan", "Milan, Italy"),
    # ("58145", "Los Angeles", "Los Angeles, California, USA"),
    # ("58146", "Chicago", "Chicago, Illinois, USA"),
    # ("131075", "Santiago", "Santiago, Chile"),
    # ("131103", "Gramado", "Gramado, Brazil"),
    # ("58156", "New Orleans", "New Orleans, Louisiana, USA"),
    # ("9641", "Seville", "Seville, Spain"),
    # ("9615", "Moscow", "Moscow, Russia"),
    # ("58153", "Honolulu", "Honolulu, Hawaii, USA"),
    # ("79299", "Marrakech", "Marrakech, Morocco"),
    # ("58045", "Toronto", "Toronto, Ontario, Canada"),
    # ("6", "Beijing", "Beijing, China"),
    # ("58162", "Boston", "Boston, Massachusetts, USA"),
    # ("81903", "Mexico City", "Mexico City, Mexico"),
    # ("58154", "Seattle", "Seattle, Washington, USA"),
    # ("16", "Ho Chi Minh City", "Ho Chi Minh City, Vietnam"),
    # ("9657", "Valencia", "Valencia, Spain"),
    # ("33", "Kuala Lumpur", "Kuala Lumpur, Malaysia"),
    # ("9645", "Munich", "Munich, Germany"),
    # ("131112", "Foz do Iguacu", "Foz do Iguacu, Brazil"),
    # ("131082", "Curitiba", "Curitiba, Brazil"),
    # ("9673", "Stockholm", "Stockholm, Sweden"),
    # ("58047", "Vancouver", "Vancouver, British Columbia, Canada"),
    # ("82575", "Melbourne", "Melbourne, Victoria, Australia"),
    # ("9", "Seoul", "Seoul, South Korea"),
    # ("8", "Hanoi", "Hanoi, Vietnam"),
    # ("9640", "Krakow", "Krakow, Poland"),
    # ("131076", "Lima", "Lima, Peru"),
    # ("135226", "Lima", "Lima, Peru"),
    # ("9650", "Turin", "Turin, Italy"),
    # ("9653", "Porto", "Porto, Portugal"),
    # ("81182", "Havana", "Havana, Cuba"),
    # ("58046", "Montreal", "Montreal, Quebec, Canada"),
    # ("58171", "Nashville", "Nashville, Tennessee, USA"),
    # ("9693", "Granada", "Granada, Spain"),
    # ("131087", "Brasilia", "Brasilia, Brazil"),
    # ("131085", "Salvador", "Salvador, Brazil"),
    # ("58058", "Niagara Falls", "Niagara Falls, Ontario, Canada"),
    # ("131084", "Montevideo", "Montevideo, Uruguay"),
    # ("10", "Shanghai", "Shanghai, China"),
    # ("58168", "San Antonio", "San Antonio, Texas, USA"),
    # ("79300", "Cape Town Central", "Cape Town Central, South Africa"),
    # ("58160", "Philadelphia", "Philadelphia, Pennsylvania, USA"),
    # ("58169", "Atlanta", "Atlanta, Georgia, USA"),
    # ("131088", "Belo Horizonte", "Belo Horizonte, Brazil"),
    # ("9704", "Dubrovnik", "Dubrovnik, Croatia"),
    # ("131091", "Fortaleza", "Fortaleza, Brazil"),
    # ("85942", "Abu Dhabi", "Abu Dhabi, United Arab Emirates"),
    # ("58180", "Miami Beach", "Miami Beach, Florida, USA"),
    # ("85941", "Jerusalem", "Jerusalem, Israel"),
    # ("9647", "Hamburg", "Hamburg, Germany"),
    # ("9642", "Warsaw", "Warsaw, Poland"),
    # ("58157", "Miami", "Miami, Florida, USA"),
    # ("131074", "Cusco", "Cusco, Peru"),
    # ("9660", "Liverpool", "Liverpool, England, UK"),
    # ("9665", "Oslo", "Oslo, Norway"),
    # ("58174", "Savannah", "Savannah, Georgia, USA"),
    # ("9651", "Glasgow", "Glasgow, Scotland, UK"),
    # ("131077", "Bogota", "Bogota, Colombia"),
    # ("58241", "Pigeon Forge", "Pigeon Forge, Tennessee, USA"),
    # ("131080", "Cartagena", "Cartagena, Colombia"),
    # ("9812", "Cordoba", "Cordoba, Argentina"),
    # ("9674", "Nice", "Nice, France"),
    # ("131151", "Campos Do Jordao", "Campos Do Jordao, Brazil"),
    # ("58224", "Memphis", "Memphis, Tennessee, USA"),
    # ("131089", "Recife", "Recife, Brazil"),
    # ("9681", "Malaga", "Malaga, Spain"),
    # ("9667", "Helsinki", "Helsinki, Finland"),
    # ("58179", "Baltimore", "Baltimore, Maryland, USA"),
    # ("9688", "Belfast", "Belfast, Northern Ireland, UK"),
    # ("131157", "Canela", "Canela, Brazil"),
    # ("82577", "Brisbane", "Brisbane, Queensland, Australia"),
    # ("131081", "Porto Alegre", "Porto Alegre, Brazil"),
    # ("44", "Phnom Penh", "Phnom Penh, Cambodia"),
    # ("58051", "Quebec City", "Quebec City, Quebec, Canada"),
    # ("9750", "Salzburg", "Salzburg, Austria"),
    # ("9675", "Marseille", "Marseille, France"),
    # ("58242", "Anaheim", "Anaheim, California, USA"),
    # ("9672", "Bologna", "Bologna, Italy"),
    # ("58176", "Tampa", "Tampa, Florida, USA"),
    # ("9682", "Cologne", "Cologne, Germany"),
    # ("58173", "Dallas", "Dallas, Texas, USA"),
    # ("58166", "Denver", "Denver, Colorado, USA"),
    # ("58188", "Sedona", "Sedona, Arizona, USA"),
    # ("146244", "Patong", "Patong, Thailand"),
    # ("9662", "Manchester", "Manchester, England, UK"),
    # ("58161", "Houston", "Houston, Texas, USA"),
    # ("10033", "Valletta", "Valletta, Malta"),
    # ("9915", "Sintra", "Sintra, Portugal"),
    # ("9761", "Benidorm", "Benidorm, Spain"),
    # ("10123", "Puerto de la Cruz", "Puerto de la Cruz, Spain"),
    # ("131119", "Ushuaia", "Ushuaia, Argentina"),
    # ("58202", "Myrtle Beach", "Myrtle Beach, South Carolina, USA"),
    # ("9680", "Palma de Mallorca", "Palma de Mallorca, Spain"),
    # ("81189", "San Juan", "San Juan, Puerto Rico"),
    # ("82582", "Wellington", "Wellington, New Zealand"),
    # ("58210", "Cleveland", "Cleveland, Ohio, USA"),
    # ("9702", "Brighton", "Brighton, England, UK"),
    # ("105", "Macau", "Macau, China"),
    # ("58275", "Williamsburg", "Williamsburg, Virginia, USA"),
    # ("131092", "Manaus", "Manaus, Brazil"),
    # ("74", "Xi'an", "Xi'an, China"),
    # ("58199", "Pittsburgh", "Pittsburgh, Pennsylvania, USA"),
    # ("58163", "Austin", "Austin, Texas, USA"),
    # ("131164", "Puerto Iguazu", "Puerto Iguazu, Brazil"),
    # ("58172", "Tucson", "Tucson, Arizona, USA"),
    # ("9659", "Riga", "Riga, Latvia"),
    # ("131104", "San Pedro de Atacama", "San Pedro de Atacama, Chile"),
    # ("58050", "Victoria", "Victoria, British Columbia, Canada"),
    # ("58196", "Louisville", "Louisville, Kentucky, USA"),
    # ("58158", "Portland", "Portland, Oregon, USA"),
    # ("9655", "Frankfurt", "Frankfurt, Germany"),
    # ("9692", "Bristol", "Bristol, England, UK"),
    # ("17", "Kathmandu", "Kathmandu, Nepal"),
    # ("9757", "Bilbao", "Bilbao, Spain"),
    # ("9852", "Toledo", "Toledo, Spain"),
    # ("81906", "Puerto Vallarta", "Puerto Vallarta, Mexico"),
    # ("58181", "Phoenix", "Phoenix, Arizona, USA"),
    # ("131162", "Punta del Este", "Punta del Este, Uruguay"),
    # ("9714", "Antwerp", "Antwerp, Belgium"),
    # ("58178", "Santa Fe", "Santa Fe, New Mexico, USA"),
    # ("131114", "Belem", "Belem, Brazil"),
    # ("46", "Jakarta", "Jakarta, Indonesia")
    # ("9646", "Bucharest", "Bucharest, Romania"),
    # ("131315", "Bonito", "Bonito, Brazil"),
    # ("81213", "Ocho Rios", "Ocho Rios, Jamaica"),
    # ("58228", "Santa Monica", "Santa Monica, California, USA"),
    # ("82579", "Christchurch", "Christchurch, New Zealand"),
    # ("131105", "Salta", "Salta, Argentina"),
    # ("58276", "Monterey", "Monterey, California, USA"),
    # ("131147", "Aracaju", "Aracaju, Brazil"),
    # ("131109", "Joao Pessoa", "Joao Pessoa, Brazil"),
    # ("10176", "Salou", "Salou, France"),
    # ("81196", "Willemstad", "Willemstad, Aruba"),
    # ("79302", "Cairo", "Cairo, Egypt"),
    # ("9719", "Rotterdam", "Rotterdam, Netherlands"),
    # ("58226", "Chattanooga", "Chattanooga, Tennessee, USA"),
    # ("137", "George Town", "George Town, Malaysia"),
    # ("131139", "El Calafate", "El Calafate, Argentina"),
    # ("9771", "Zaragoza", "Zaragoza, Spain"),
    # ("58219", "Kansas City", "Kansas City, Missouri, USA"),
    # ("9695", "Vilnius", "Vilnius, Lithuania"),
    # ("52", "Yangon (Rangoon)", "Yangon (Rangoon), Myanmar"),
    # ("58476", "Page", "Page, Arizona, USA"),
    # ("9717", "Dresden", "Dresden, Germany"),
    # ("58048", "Calgary", "Calgary, Alberta, Canada"),
    # ("85946", "Doha", "Doha, Qatar"),
    # ("79316", "Luxor", "Luxor, Egypt"),
    # ("58164", "Brooklyn", "Brooklyn, New York, USA"),
    # ("58203", "Lahaina", "Lahaina, Hawaii, USA"),
    # ("131108", "Ubatuba", "Ubatuba, Brazil"),
    # ("49", "Da Nang", "Da Nang, Vietnam"),
    # ("9950", "Pompeii", "Pompeii, Italy"),
    # ("9721", "Antalya", "Antalya, Turkey"),
    # ("58177", "Fort Lauderdale", "Fort Lauderdale, Florida, USA"),
    # ("58068", "Banff", "Banff, Alberta, Canada"),
    # ("9722", "Gdansk", "Gdansk, Poland"),
    # ("131395", "Praia da Pipa", "Praia da Pipa, Brazil"),
    # ("58231", "Clearwater", "Clearwater, Florida, USA"),
    # ("9638", "Kyiv", "Kyiv, Ukraine"),
    # ("82586", "Hobart", "Hobart, Tasmania, Australia"),
    # ("93", "Nha Trang", "Nha Trang, Vietnam"),
    # ("9703", "Ljubljana", "Ljubljana, Slovenia"),
    # ("9658", "Tbilisi", "Tbilisi, Georgia"),
    # ("58201", "Cincinnati", "Cincinnati, Ohio, USA"),
    # ("9875", "Salamanca", "Salamanca, Spain"),
    # ("9669", "Zagreb", "Zagreb, Croatia"),
    # ("187", "Melaka", "Melaka, Malaysia"),
    # ("58286", "Gettysburg", "Gettysburg, Pennsylvania, USA"),
    # ("9772", "Alicante", "Alicante, Spain"),
    # ("82584", "Cairns", "Cairns, Queensland, Australia"),
    # ("92", "Hue", "Hue, Vietnam"),
    # ("147352", "La Jolla", "La Jolla, California, USA"),
    # ("9753", "Wroclaw", "Wroclaw, Poland"),
    # ("9737", "Stuttgart", "Stuttgart, Germany"),
    # ("131110", "Mar del Plata", "Mar del Plata, Argentina"),
    # ("131122", "Santos", "Santos, Brazil"),
    # ("58195", "Milwaukee", "Milwaukee, Wisconsin, USA"),
    # ("9739", "Nuremberg", "Nuremberg, Germany"),
    # ("58269", "Moab", "Moab, Utah, USA"),
    # ("82588", "Darwin", "Darwin, Northern Territory, Australia"),
    # ("79321", "Giza", "Giza, Egypt"),
    # ("10230", "Segovia", "Segovia, Spain"),
    # ("9744", "Ghent", "Ghent, Belgium"),
    # ("128", "Hua Hin", "Hua Hin, Thailand"),
    # ("58059", "Halifax", "Halifax, Nova Scotia, Canada"),
    # ("61", "Busan", "Busan, South Korea"),
    # ("62", "Kanazawa", "Kanazawa, Japan"),
    # ("9841", "Bournemouth", "Bournemouth, England, UK"),
    # ("58205", "Indianapolis", "Indianapolis, Indiana, USA"),
    # ("9849", "Bergamo", "Bergamo, Italy"),
    # ("58185", "Asheville", "Asheville, North Carolina, USA"),
    # ("81197", "Santo Domingo", "Santo Domingo, Dominican Republic"),
    # ("58216", "Salt Lake City", "Salt Lake City, Utah, USA"),
    # ("58079", "North Vancouver", "North Vancouver, British Columbia, Canada"),
    # ("9819", "Rhodes Town", "Rhodes Town, Greece"),
    # ("131099", "Arequipa", "Arequipa, Peru"),
    # ("131125", "Niteroi", "Niteroi, Brazil"),
    # ("58189", "Naples", "Naples, Italy"),
    # ("58342", "Arlington", "Arlington, Virginia, USA"),
    # ("10260", "Selcuk", "Selcuk, Turkey"),
    # ("58218", "Detroit", "Detroit, Michigan, USA"),
    # ("58184", "Minneapolis", "Minneapolis, Minnesota, USA"),
    # ("131127", "Vitoria", "Vitoria, Brazil"),
    # ("146468", "Carcassonne Center", "Carcassonne Center, France"),
    # ("131438", "Morro de Sao Paulo", "Morro de Sao Paulo, Brazil"),
    # ("58748", "Titusville", "Titusville, Florida, USA"),
    # ("10143", "Torquay", "Torquay, England, UK"),
    # ("58192", "Scottsdale", "Scottsdale, Arizona, USA"),
    # ("99", "Nara", "Nara, Japan"),
    # ("50", "Naha", "Naha, Taiwan"),
    # ("39", "Guangzhou", "Guangzhou, China"),
    # ("131146", "Cabo Frio", "Cabo Frio, Brazil"),
    # ("81941", "Akumal", "Akumal, Mexico"),
    # ("58244", "Galveston", "Galveston, Texas, USA"),
    # ("9942", "Heidelberg", "Heidelberg, Germany"),
    # ("58232", "Oklahoma City", "Oklahoma City, Oklahoma, USA"),
    # ("10015", "Ronda", "Ronda, Spain"),
    # ("257", "Chiang Rai", "Chiang Rai, Thailand"),
    # ("58190", "Kailua-Kona", "Kailua-Kona, Hawaii, USA"),
    # ("175", "Manila", "Manila, Philippines"),
    # ("9857", "Marmaris", "Marmaris, Turkey"),
    # ("9785", "Evora", "Evora, Portugal"),
    # ("76078", "Lake Louise", "Lake Louise, Alberta, Canada"),
    # ("131389", "San Andres", "San Andres, Colombia"),
    # ("146242", "Chalong", "Chalong, Thailand"),
    # ("58212", "Fort Worth", "Fort Worth, Texas, USA"),
    # ("67", "Chengdu", "Chengdu, China"),
    # ("58193", "Charlotte", "Charlotte, North Carolina, USA"),
    # ("75", "Nagasaki", "Nagasaki, Japan"),
    # ("81911", "Oaxaca", "Oaxaca, Mexico"),
    # ("9899", "Coimbra", "Coimbra, Portugal"),
    # ("9738", "Dusseldorf", "Dusseldorf, Germany"),
    # ("58206", "Santa Barbara", "Santa Barbara, California, USA"),
    # ("131178", "Pocos de Caldas", "Pocos de Caldas, Brazil"),
    # ("131098", "Valparaiso", "Valparaiso, Chile"),
    # ("82", "Baku", "Baku, Azerbaijan"),
    # ("9708", "Sheffield", "Sheffield, England, UK"),
    # ("11489", "Mont-Saint-Michel", "Mont-Saint-Michel, France"),
    # ("64", "Hangzhou", "Hangzhou, China"),
    # ("10171", "Nerja", "Nerja, Spain"),
    # ("10792", "Monte-Carlo", "Monte-Carlo, Monaco"),
    # ("58289", "Salem", "Salem, Oregon, USA"),
    # ("58222", "Richmond", "Richmond, Virginia, USA"),
    # ("79305", "Fes", "Fes, Morocco"),
    # ("10595", "Peterhof", "Peterhof, Russia"),
    # ("58052", "Edmonton", "Edmonton, Alberta, Canada"),
    # ("131626", "Penha", "Penha, Brazil"),
    # ("131095", "La Paz", "La Paz, Bolivia"),
    # ("131113", "Rosario", "Rosario, Argentina"),
    # ("81913", "Merida", "Merida, Mexico"),
    # ("12525", "Stretford", "Stretford, England, UK"),
    # ("81912", "Guadalajara", "Guadalajara, Mexico"),
    # ("9896", "Goreme", "Goreme, Turkey"),
    # ("9830", "Heraklion", "Heraklion, Greece"),
    # ("73", "Yerevan", "Yerevan, Armenia"),
    # ("131175", "Itacare", "Itacare, Brazil"),
    # ("131327", "Bombinhas", "Bombinhas, Brazil"),
    # ("58309", "Hilo", "Hilo, Hawaii, USA"),
    # ("9827", "Cannes", "Cannes, France"),
    # ("131140", "Puno", "Puno, Peru"),
    # ("131107", "Santa Marta", "Santa Marta, Colombia"),
    # ("110", "Hakodate", "Hakodate, Japan"),
    # ("58211", "Fort Myers", "Fort Myers, Florida, USA"),
    # ("131131", "Sao Luis", "Sao Luis, Brazil"),
    # ("43", "Colombo", "Colombo, Sri Lanka"),
    # ("81918", "Puebla", "Puebla, Mexico"),
    # ("79308", "Casablanca", "Casablanca, Morocco"),
    # ("9887", "Cadiz", "Cadiz, Spain"),
    # ("131447", "Caldas Novas", "Caldas Novas, Brazil"),
    # ("58345", "Wisconsin Dells", "Wisconsin Dells, Wisconsin, USA"),
    # ("10134", "Burgos", "Burgos, Spain"),
    # ("81219", "Puerto Plata", "Puerto Plata, Dominican Republic"),
    # ("9769", "Kaliningrad", "Kaliningrad, Russia"),
    # ("131145", "Blumenau", "Blumenau, Brazil"),
    # ("10241", "Playa Blanca", "Playa Blanca, Nicaragua"),
    # ("12491", "Mdina", "Mdina, Malta"),
    # ("58213", "Omaha", "Omaha, Nebraska, USA"),
    # ("81924", "Guanajuato", "Guanajuato, Mexico"),
    # ("954", "Pecatu", "Pecatu, Indonesia"),
    # ("10106", "Torremolinos", "Torremolinos, Spain"),
    # ("9843", "Gothenburg", "Gothenburg, Sweden"),
    # ("145", "Kota Kinabalu", "Kota Kinabalu, Malaysia"),
    # ("133", "Bandung", "Bandung, Indonesia"),
    # ("9705", "Ankara", "Ankara, Turkey"),
    # ("131177", "Tiradentes", "Tiradentes, Brazil"),
    # ("9984", "Bern", "Bern, Switzerland"),
    # ("468", "Ayutthaya", "Ayutthaya, Thailand"),
    # ("10031", "Lloret de Mar", "Lloret de Mar, Spain"),
    # ("9817", "Basel", "Basel, Switzerland"),
    # ("58284", "Fredericksburg", "Fredericksburg, Virginia, USA"),
    # ("174", "Da Lat", "Da Lat, Vietnam"),
    # ("78746", "San Jose", "San Jose, Costa Rica"),
    # ("9715", "Nottingham", "Nottingham, England, UK"),
    # ("131138", "Puerto Varas", "Puerto Varas, Chile"),
    # ("131337", "Guaruja", "Guaruja, Brazil"),
    # ("9886", "Santander", "Santander, Spain"),
    # ("58300", "Flagstaff", "Flagstaff, Arizona, USA"),
    # ("9804", "Sarajevo", "Sarajevo, Bosnia and Herzegovina"),
    # ("59165", "Keystone", "Keystone, Colorado, USA"),
    # ("58248", "Daytona Beach", "Daytona Beach, Florida, USA"),
    # ("9928", "Malmo", "Malmo, Sweden"),
    # ("131106", "Campinas", "Campinas, Brazil"),
    # ("82950", "Waitomo Caves", "Waitomo Caves, New Zealand"),
    # ("60831", "Hammond", "Hammond, Indiana, USA"),
    # ("59140", "Poipu", "Poipu, Hawaii, USA"),
    # ("147376", "Saint Augustine Beach", "Saint Augustine Beach, Florida, USA"),
    # ("116", "Nikko", "Nikko, Japan"),
    # ("12573", "Pamukkale", "Pamukkale, Turkey"),
    # ("58370", "Rapid City", "Rapid City, South Dakota, USA"),
    # ("58368", "Carlsbad", "Carlsbad, California, USA"),
    # ("85943", "Tehran", "Tehran, Iran"),
    # ("78760", "Manuel Antonio", "Manuel Antonio, Costa Rica"),
    # ("188", "Cebu City", "Cebu City, Philippines"),
    # ("9701", "Nizhny Novgorod", "Nizhny Novgorod, Russia"),
    # ("292", "Vientiane", "Vientiane, Laos"),
    # ("10979", "Merida", "Merida, Mexico"),
    # ("10101", "Puerto Del Carmen", "Puerto Del Carmen, Mexico"),
    # ("131102", "Guayaquil", "Guayaquil, Ecuador"),
    # ("58314", "Hot Springs", "Hot Springs, Arkansas, USA"),
    # ("10698", "Oia", "Oia, Greece"),
    # ("121", "Kamakura", "Kamakura, Japan"),
    # ("10058", "Potsdam", "Potsdam, Germany"),
    # ("85945", "Beirut", "Beirut, Lebanon"),
    # ("58949", "Hershey", "Hershey, Pennsylvania, USA"),
    # ("10696", "Bonifacio", "Bonifacio, Philippines"),
    # ("584", "Kanchanaburi", "Kanchanaburi, Thailand"),
    # ("58053", "Winnipeg", "Winnipeg, Manitoba, Canada"),
    # ("82615", "Taupo", "Taupo, New Zealand"),
    # ("131332", "Vila Velha", "Vila Velha, Brazil"),
    # ("10229", "Nimes", "Nimes, France"),
    # ("12927", "Oswiecim", "Oswiecim, Poland"),
    # ("13458", "Akrotiri", "Akrotiri, Cyprus"),
    # ("9956", "Mykonos Town", "Mykonos Town, Greece"),
    # ("58299", "Fort Myers Beach", "Fort Myers Beach, Florida, USA"),
    # ("85", "Suzhou", "Suzhou, China"),
    # ("58214", "Sacramento", "Sacramento, California, USA"),
    # ("223", "Kuching", "Kuching, Malaysia"),
    # ("9790", "Lviv", "Lviv, Ukraine"),
    # ("81981", "Palenque", "Palenque, Mexico"),
    # ("131180", "Puerto Ayora", "Puerto Ayora, Ecuador"),
    # ("209", "Thimphu", "Thimphu, Bhutan"),
    # ("131362", "Cafayate", "Cafayate, Argentina"),
    # ("10030", "Bursa", "Bursa, Turkey"),
    # ("95", "Kumamoto", "Kumamoto, Japan"),
    # ("450", "Paro", "Paro, Bhutan"),
    # ("465", "Gyeongju", "Gyeongju, South Korea"),
    # ("330", "Tashkent", "Tashkent, Uzbekistan"),
    # ("81250", "Santiago de Cuba", "Santiago de Cuba, Cuba"),
    # ("9952", "Plovdiv", "Plovdiv, Bulgaria"),
    # ("13", "New Delhi", "New Delhi, India"),
    # ("25", "Mumbai", "Mumbai, India"),
    # ("60", "Agra", "Agra, India"),
    # ("35", "Bengaluru", "Bengaluru, India"),
    # ("78", "Hyderabad", "Hyderabad, India"),
    # ("91", "Udaipur", "Udaipur, India"),
    # ("69", "Kolkata (Calcutta)", "Kolkata (Calcutta), India"),
    # ("40", "Chennai (Madras)", "Chennai (Madras), India"),
    # ("146238", "Amer", "Amer, India"),
    # ("57", "Pune", "Pune, India"),
    # ("122", "Varanasi", "Varanasi, India"),
    # ("161", "Ahmedabad", "Ahmedabad, India"),
    # ("143", "Jodhpur", "Jodhpur, India"),
    # ("256", "Srinagar", "Srinagar, India"),
    # ("480", "Ooty (Udhagamandalam)", "Ooty (Udhagamandalam), India"),
    # ("183", "Jaisalmer", "Jaisalmer, India"),
    # ("503", "Gangtok", "Gangtok, India"),
    # ("384", "Amritsar", "Amritsar, India"),
    # ("146271", "Manali", "Manali, India"),
    # ("349", "Darjeeling", "Darjeeling, India"),
    # ("334", "Pondicherry", "Pondicherry, India"),
    # ("589", "Port Blair", "Port Blair, India"),
    # ("287", "Panjim", "Panjim, India"),
    # ("200", "Thiruvananthapuram (Trivandrum)", "Thiruvananthapuram (Trivandrum), India"),
    # ("207", "Gurugram (Gurgaon)", "Gurugram (Gurgaon), India"),
    # ("518", "Visakhapatnam", "Visakhapatnam, India"),
    # ("1055", "Mahabalipuram", "Mahabalipuram, India"),
    # ("975", "Puri", "Puri, India"),
    # ("696", "Hampi", "Hampi, India"),
    # ("687", "Mussoorie", "Mussoorie, India"),
    # ("895", "Nainital", "Nainital, India"),
    # ("978", "Mahabaleshwar", "Mahabaleshwar, India"),
    # ("1222", "Kalpetta", "Kalpetta, India"),
    # ("926", "Kanyakumari", "Kanyakumari, India"),
    # ("146282", "McLeod Ganj", "McLeod Ganj, India"),
    # ("615", "Madurai", "Madurai, India"),
    # ("194", "Rishikesh", "Rishikesh, India"),
    # ("877", "Mount Abu", "Mount Abu, India"),
    # ("607", "Aurangabad", "Aurangabad, India"),
    # ("375", "Lucknow", "Lucknow, India"),
    # ("449", "Nashik", "Nashik, India"),
    # ("728", "Shillong", "Shillong, India"),
    # ("1325", "Rameswaram", "Rameswaram, India"),
    # ("1886", "Madikeri", "Madikeri, India"),
    # ("485", "Bhopal", "Bhopal, India"),
    # ("444", "Bhubaneswar", "Bhubaneswar, India"),
    # ("1138", "Sawai Madhopur", "Sawai Madhopur, India"),
    # ("348", "Vadodara", "Vadodara, India"),
    # ("558", "Indore", "Indore, India"),
    # ("371", "Coimbatore", "Coimbatore, India"),
    # ("914", "Tirupati", "Tirupati, India"),
    # ("722", "Pushkar", "Pushkar, India"),
    # ("524", "Guwahati", "Guwahati, India"),
    # ("850", "Khajuraho", "Khajuraho, India"),
    # ("350", "Alappuzha", "Alappuzha, India"),
    # ("1966", "Kovalam", "Kovalam, India"),
    # ("479", "Mangalore", "Mangalore, India"),
    # ("1316", "Shirdi", "Shirdi, India"),
    # ("1006", "Gulmarg", "Gulmarg, India"),
    # ("472", "Navi Mumbai", "Navi Mumbai, India"),
    # ("1435", "Yercaud", "Yercaud, India"),
    # ("662", "Varkala Town", "Varkala Town, India"),
    # ("563", "Noida", "Noida, India"),
    # ("1089", "Bikaner", "Bikaner, India"),
    # ("1983", "Dwarka", "Dwarka, India"),
    # ("993", "Bhuj", "Bhuj, India"),
    # ("1025", "Ujjain", "Ujjain, India"),
    # ("1743", "Diu", "Diu, India"),
    # ("1874", "Vrindavan", "Vrindavan, India"),
    # ("981", "Jammu City", "Jammu City, India"),
    # ("805", "Tiruchirappalli", "Tiruchirappalli, India"),
    # ("1887", "Coonoor", "Coonoor, India"),
    # ("738", "Thanjavur", "Thanjavur, India"),
    # ("1291", "Gwalior", "Gwalior, India"),
    # ("673", "Patna", "Patna, India"),
    # ("478", "Surat", "Surat, India"),
    # ("1784", "Dalhousie", "Dalhousie, India"),
    # ("1015", "Kolhapur", "Kolhapur, India"),
    # ("2371", "Gokarna", "Gokarna, India"),
    # ("1241", "Alwar", "Alwar, India")
    # ("1365", "Bodh Gaya", "Bodh Gaya, India"),
    # ("1750", "Somnath", "Somnath, India"),
    # ("536", "Thrissur", "Thrissur, India"),
    # ("398", "Nagpur", "Nagpur, India"),
    # ("2824", "Arpora", "Arpora, India"),
    # ("1000", "Udupi", "Udupi, India"),
    # ("1808", "Daman", "Daman, India"),
    # ("1215", "Pachmarhi", "Pachmarhi, India"),
    # ("2791", "Lansdowne", "Lansdowne, India"),
    # ("2027", "Orchha", "Orchha, India"),
    # ("527", "Kozhikode", "Kozhikode, India"),
    # ("1406", "Jabalpur", "Jabalpur, India"),
    # ("1667", "Matheran", "Matheran, India"),
    # ("785", "Allahabad", "Allahabad, India"),
    # ("1942", "Shimoga", "Shimoga, India"),
    # ("146301", "Khandala", "Khandala, India"),
    # ("994", "Junagadh", "Junagadh, India"),
    # ("1529", "Chittaurgarh", "Chittaurgarh, India"),
    # ("2178", "Panchgani", "Panchgani, India"),
    # ("2149", "Arambol", "Arambol, India"),
    # ("1480", "Alibaug", "Alibaug, India"),
    # ("1002", "Mathura", "Mathura, India"),
    # ("1302", "Kumbakonam", "Kumbakonam, India"),
    # ("1407", "Kalimpong", "Kalimpong, India"),
    # ("1573", "Tawang", "Tawang, India"),
    # ("976", "Kanchipuram", "Kanchipuram, India"),
    # ("3369", "Konark", "Konark, India"),
    # ("1212", "Vijayawada", "Vijayawada, India"),
    # ("894", "Rajkot", "Rajkot, India"),
    # ("2711", "Auroville", "Auroville, India"),
    # ("1159", "Bundi", "Bundi, India"),
    # ("146275", "Anjuna", "Anjuna, India"),
    # ("1177", "Ranchi", "Ranchi, India"),
    # ("798", "Raipur", "Raipur, India"),
    # ("714", "Kollam", "Kollam, India"),
    # ("1540", "Ponda", "Ponda, India"),
    # ("1463", "Vellore", "Vellore, India"),
    # ("1444", "Malvan", "Malvan, India"),
    # ("979", "Palakkad", "Palakkad, India"),
    # ("830", "Dehradun", "Dehradun, India")
    # ("1059", "Idukki", "Idukki, India"),
    # ("2401", "Silvassa", "Silvassa, India"),
    # ("982", "Ratnagiri", "Ratnagiri, India"),
    # ("730", "Jamnagar", "Jamnagar, India"),
    # ("2540", "Kumarakom", "Kumarakom, India"),
    # ("1473", "Kutch", "Kutch, India"),
    # ("1863", "Kullu", "Kullu, India"),
    # ("2177", "Gandhinagar", "Gandhinagar, India"),
    # ("1765", "Almora", "Almora, India"),
    # ("1763", "Jamshedpur", "Jamshedpur, India"),
    # ("1135", "Kanpur", "Kanpur, India"),
    # ("3129", "Digha", "Digha, India"),
    # ("1852", "Kurnool", "Kurnool, India"),
    # ("849", "Kottayam", "Kottayam, India"),
    # ("948", "Satara", "Satara, India"),
    # ("1013", "Imphal", "Imphal, India"),
    # ("1668", "Hassan", "Hassan, India"),
    # ("1442", "Warangal", "Warangal, India"),
    # ("1251", "Salem", "Salem, India"),
    # ("2185", "Kargil", "Kargil, India"),
    # ("2919", "Badrinath", "Badrinath, India"),
    # ("3260", "Bhimtal", "Bhimtal, India"),
    # ("909", "Agartala", "Agartala, India"),
    # ("1679", "Panchkula", "Panchkula, India"),
    # ("923", "Ghaziabad", "Ghaziabad, India"),
    # ("1163", "Jalandhar", "Jalandhar, India"),
    # ("1218", "Kota", "Kota, India"),
    # ("1331", "Porbandar", "Porbandar, India"),
    # ("1114", "Siliguri", "Siliguri, India"),
    # ("1581", "Hubli-Dharwad", "Hubli-Dharwad, India"),
    # ("2141", "Kohima", "Kohima, India"),
    # ("3466", "Patnitop", "Patnitop, India"),
    # ("1812", "Patiala", "Patiala, India"),
    # ("2040", "Kurukshetra", "Kurukshetra, India"),
    # ("1418", "Mandi", "Mandi, India"),
    # ("1306", "Faridabad", "Faridabad, India"),
    # ("85939", "Dubai", "United Arab Emirates"),
    # ("9630", "Florence", "Italy"),
    # ("9636", "Edinburgh", "United Kingdom"),
    # ("82574", "Sydney", "Australia"),
    # ("15", "Hong Kong", "China"),
    # ("9618", "St. Petersburg", "Russia"),
    # ("2", "Kyoto", "Japan"),
    # ("9637", "Athens", "Greece"),
    # ("58150", "San Diego", "United States"),
    # ("9643", "Copenhagen", "Denmark"),
    # ("11", "Siem Reap", "Cambodia"),
    # ("9635", "Naples", "Italy"),
    # ("9649", "Brussels", "Belgium"),
    # ("81905", "Playa del Carmen", "Mexico"),
    # ("9707", "York", "United Kingdom"),
    # ("131100", "Natal", "Brazil"),
    # ("3", "Osaka", "Japan"),
    # ("131086", "Florianopolis", "Brazil"),
    # ("18", "Taipei", "Taiwan"),
    # ("131118", "Porto Seguro", "Brazil"),
    # ("82576", "Auckland", "New Zealand"),
    # ("9745", "Bruges", "Belgium"),
    # ("9798", "Blackpool", "United Kingdom"),
    # ("58183", "Branson", "United States"),
    # ("22", "Ubud", "Indonesia"),
    # ("78744", "Panama City", "Panama"),
    # ("24", "Jaipur", "India"),
    # ("9656", "Reykjavik", "Iceland"),
    # ("82578", "Gold Coast", "Australia"),
    # ("58170", "Charleston", "United States"),
    # ("53", "Kathu", "Thailand"),
    # ("9711", "Verona", "Italy"),
    # ("58175", "Saint Louis", "United States"),
    # ("9683", "Genoa", "Italy"),
    # ("9666", "Birmingham", "United Kingdom"),
    # ("9670", "Lyon", "France"),
    # ("9735", "Funchal", "Portugal"),
    # ("80", "Pattaya", "Thailand"),
    # ("9730", "Bath", "United Kingdom"),
    # ("81904", "Cancun", "Mexico"),
    # ("81180", "Punta Cana", "Caribbean"),
    # ("9654", "Palermo", "Italy"),
    # ("9679", "Tallinn", "Estonia"),
    # ("131150", "Ipojuca", "Brazil"),
    # ("131090", "San Carlos de Bariloche", "Argentina"),
    # ("81909", "Tulum", "Mexico"),
    # ("21", "Hoi An", "Vietnam"),
    # ("19", "Chiang Mai", "Thailand"),
    # ("131083", "Mendoza", "Argentina"),
    # ("9767", "Pisa", "Italy"),
    # ("131078", "Quito", "Ecuador"),
    # ("131132", "Petropolis", "Brazil"),
    # ("37", "Kuta", "Indonesia"),
    # ("131115", "Maceio", "Brazil"),
    # ("79", "Krabi Town", "Thailand"),
    # ("131134", "Jijoca de Jericoacoara", "Brazil"),
    # ("28", "Taito", "Japan"),
    # ("131094", "Paraty", "Brazil"),
    # ("9712", "Cardiff", "United Kingdom"),
    # ("9792", "Maspalomas", "Spain"),
    # ("82593", "Rotorua", "New Zealand"),
    # ("9826", "Adeje", "Spain"),
    # ("9800", "Syracuse", "Italy"),
    # ("9751", "Strasbourg", "France"),
    # ("9663", "Bordeaux", "France"),
    # ("9763", "Paphos", "Cyprus"),
    # ("82585", "Canberra", "Australia"),
    # ("9802", "Siena", "Italy"),
    # ("9696", "Bratislava", "Slovakia"),
    # ("23", "Minato", "Japan"),
    # ("10219", "Windsor", "United Kingdom"),
    # ("29", "Sapporo", "Japan"),
    # ("9803", "Portsmouth", "United Kingdom"),
    # ("9668", "Zurich", "Switzerland"),
    # ("85940", "Tel Aviv", "Israel"),
    # ("10061", "Versailles", "France"),
    # ("38", "Shibuya", "Japan"),
    # ("58187", "Sarasota", "United States"),
    # ("9801", "Bergen", "Norway"),
    # ("131079", "Medellin", "Colombia"),
    # ("184", "Luang Prabang", "Laos"),
    # ("79309", "Sharm El Sheikh", "Egypt"),
    # ("9850", "Chester", "United Kingdom"),
    # ("131318", "Machu Picchu", "Peru"),
    # ("20", "Yokohama", "Japan"),
    # ("58049", "Ottawa", "Canada"),
    # ("81226", "Varadero", "Caribbean"),
    # ("9724", "Geneva", "Switzerland"),
    # ("58182", "Greater Palm Springs", "United States"),
    # ("10008", "Lucerne", "Switzerland"),
    # ("9690", "Padua", "Italy"),
    # ("9889", "Benalmadena", "Spain"),
    # ("82581", "Adelaide", "Australia"),
    # ("9723", "Oxford", "United Kingdom"),
    # ("9836", "Killarney", "Ireland"),
    # ("9677", "Sochi", "Russia"),
    # ("58191", "Albuquerque", "United States"),
    # ("51", "Phuket Town", "Thailand"),
    # ("32", "Shinjuku", "Japan"),
    # ("9765", "Albufeira", "Portugal"),
    # ("42", "Chiyoda", "Japan"),
    # ("59", "Hiroshima", "Japan"),
    # ("131093", "Angra Dos Reis", "Brazil"),
    # ("9840", "Lucca", "Italy"),
    # ("9689", "Leeds", "United Kingdom"),
    # ("81194", "Nassau", "Caribbean"),
    # ("10046", "Ravenna", "Italy"),
    # ("9687", "Belgrade", "Serbia"),
    # ("131117", "Ouro Preto", "Brazil"),
    # ("9725", "The Hague", "The Netherlands"),
    # ("9691", "Trieste", "Italy"),
    # ("9694", "Split", "Croatia"),
    # ("9891", "Matera", "Italy"),
    # ("9935", "Taormina", "Italy"),
    # ("9998", "Llandudno", "United Kingdom"),
    # ("79306", "Johannesburg", "South Africa"),
    # ("11769", "Lindos", "Greece"),
    # ("58198", "Anchorage", "United States"),
    # ("9709", "Toulouse", "France"),
    # ("9676", "Sofia", "Bulgaria"),
    # ("9838", "Santiago de Compostela", "Spain"),
    # ("9945", "Assisi", "Italy"),
    # ("9756", "Rimini", "Italy"),
    # ("30", "Nagoya", "Japan"),
    # ("9799", "Nantes", "France"),
    # ("41", "New Taipei", "Taiwan"),
    # ("10074", "Agrigento", "Italy"),
    # ("176", "Karon", "Thailand"),
    # ("9903", "Carcassonne", "France"),
    # ("68", "Kochi (Cochin)", "India"),
    # ("131478", "Mata de Sao Joao", "Brazil"),
    # ("78752", "La Fortuna de San Carlos", "Costa Rica"),
    # ("9713", "Newcastle upon Tyne", "United Kingdom"),
    # ("34", "Kobe", "Japan"),
    # ("79303", "Nairobi", "Kenya"),
    # ("9919", "Avignon", "France"),
    # ("131360", "Maragogi", "Brazil"),
    # ("82594", "Dunedin", "New Zealand"),
    # ("31", "Fukuoka", "Japan"),
    # ("10064", "Weymouth", "United Kingdom"),
    # ("10235", "Bled", "Slovenia"),
    # ("10211", "Vila Nova de Gaia", "Portugal"),
    # ("118", "Kandy", "Sri Lanka"),
    # ("9937", "Scarborough", "United Kingdom"),
    # ("9861", "Innsbruck", "Austria"),
    # ("9917", "Lincoln", "United Kingdom"),
    # ("9727", "Thessaloniki", "Greece"),
    # ("9734", "Galway", "Ireland"),
    # ("98", "Bophut", "Thailand"),
    # ("412", "Munnar", "India"),
    # ("297", "Leh", "India"),
    # ("313", "Manali Tehsil", "India"),
    # ("428", "Shimla", "India"),
    # ("842", "Kodaikanal", "India"),
    # ("405", "Dharamsala", "India"),
    # ("304", "Chandigarh", "India"),
    # ("753", "Thekkady", "India"),
    # ("701", "Lonavala", "India"),
    # ("329", "Bardez", "India"),
    # ("783", "Haridwar", "India"),
    # ("1868", "Baga", "India"),
    # ("787", "Chikmagalur", "India"),
    # ("814", "Canacona", "India"),
    # ("2253", "Pahalgam", "India"),
    # ("956", "Ajmer", "India"),
    # ("461", "Kannur", "India"),
    # ("541", "Thane", "India"),
    # ("2397", "Kasauli", "India"),
    # ("3684", "Kandaghat Tehsil", "India"),
    # ("1673", "Palampur", "India"),
    # ("2477", "Auli", "India")
    #     ("2643", "Ayodhya", "India"),
    # ("4655", "Velankanni", "India"),
    # ("3396", "Ambaji", "India"),
    # ("2976", "Katra", "India"),
    # ("4318", "Dharmasthala", "India"),
    # ("4300", "Pavagadh", "India"),
    # ("2936", "Thiruvannamalai", "India"),
    # ("1729", "Gaya", "India"),
    # ("3900", "Pandharpur", "India"),
    # ("3710", "Srisailam", "India"),
    # ("4276", "Kedarnath", "India"),
    # ("581", "Calangute", "India"),
    # ("1664", "Fatehpur Sikri", "India"),
    # ("4947", "Gangotri", "India"),
    # ("8658", "Ajanta", "India"),
    # ("2953", "Nalanda", "India"),
    # ("2707", "Sanchi", "India"),
    # ("2562", "Jhansi", "India"),
    # ("4497", "Araku Valley", "India"),
    # ("2839", "Sonamarg", "India"),
    # ("8980", "Dawki", "India"),
    # ("7184", "Sasan Gir", "India"),
    # ("3376", "Manipal", "India"),
    # ("2083", "Howrah", "India"),
    # ("2231", "Guruvayur", "India"),
    # ("3635", "Nathdwara", "India"),
    # ("8658","Ajanta","India"),
    # ("6474", "Sinquerim", "India"),
    # ("3639", "Colva", "India"),
    # ("2084", "Cavelossim", "India"),
    # ("3543", "Bharatpur", "India"),
    # ("2941", "Benaulim", "India"),
    # ("2231", "Guruvayur", "India"),
    # ("4705", "Rajsamand", "India"),
    # ("5592", "Varca", "India"),
    # ("2644", "Morjim", "India"),
    # ("4957", "Mararikulam", "India"),
    # ("1854", "Saputara", "India"),
    # ("4656", "Lachung", "India"),
    # ("1402", "Chamba", "India"),
    # ("3110", "Badami", "India"),
    # ("7541", "Belur", "India"),
    # ("1083", "Mandu", "India"),
    # ("2776", "Chikkaballapur", "India"),
    # ("5126", "Vythiri", "India"),
    # ("1555", "Bijapur", "India"),
    # ("7167", "Abhaneri", "India"),
    # ("3089", "Mandrem", "India"),
    # ("3354", "Kausani", "India"),
    # ("146272", "Naggar", "India"),
    # ("7513", "Kanoi", "India"),
    # ("8421", "Chapora", "India"),
    # ("3127", "Mukteshwar", "India"),
    # ("4594", "Athirappilly", "India"),
    # ("4414", "Dona Paula", "India"),
    # ("4639", "Bandipur", "India"),
    # ("1312", "Kasaragod", "India"),
    # ("827", "Tirunelveli", "India"),
    # ("1436", "Murshidabad", "India"),
    # ("2885", "Srirangapatna", "India"),
    # ("1479", "Karwar", "India"),
    # ("146303", "Kumily", "India"),
    # ("2731", "Ranikhet", "India"),
    # ("9024", "Mandarmani", "India"),
    # ("2654", "Valparai", "India"),
    # ("4744", "Halebid", "India"),
    # ("8767", "Bhimashankar", "India"),
    # ("4995", "Mawlynnong", "India"),
    # ("3635", "Nathdwara", "India"),
    # ("1561", "Kangra", "India"),
    # ("2692", "Ravangla", "India"),
    # ("2760", "Dapoli", "India"),
    # ("5464", "Kashid", "India"),
    # ("4655", "Velankanni", "India"),
    # ("8064", "Deshnoke", "India"),
    # ("1250", "Mandya", "India"),
    # ("3404", "Sangla", "India"),
    # ("3710", "Srisailam", "India"),
    # ("2936", "Thiruvannamalai", "India"),
    # ("6608", "Belakavadi", "India"),
    # ("1699", "Margao", "India"),
    # ("3197", "Vagamon", "India"),
    # ("6897", "Utorda", "India"),
    # ("2935", "Yelagiri", "India"),
    # ("2336", "Chamoli", "India"),
    # ("7824", "Malsi", "India"),
    # ("1183", "Raigad", "India"),
    # ("5492", "Lepakshi", "India"),
    # ("7536", "Kottagudi", "India"),
    # ("5776", "Belur", "India"),
    # ("3230", "Murdeshwar", "India"),
    # ("146277", "Candolim", "India"),
    # ("4195", "Dandeli", "India"),
    # ("5422", "Dhanaulti", "India"),
    # ("2609", "Santiniketan", "India"),
    # ("3187", "Mandvi", "India"),
    # ("6377", "Magadi", "India"),
    # ("2121", "Deoghar", "India"),
    # ("4238", "Mandla", "India"),
    # ("4467", "Kaushambi", "India"),
    # ("3419", "Chidambaram", "India"),
    # ("5833", "Daulatabad", "India"),
    # ("1659", "Vasco da Gama", "India"),
    # ("1949", "Greater Noida", "India"),
    # ("959", "Midnapore", "India"),
    # ("1531", "Ahmednagar", "India"),
    # ("5779", "Bhagamandala", "India"),
    # ("1729", "Gaya", "India"),
    # ("4528", "Kaza", "India"),
    # ("1754", "Bharuch", "India"),
    # ("3446", "Palani", "India"),
    # ("1776", "Rajgir", "India"),
    # ("4692", "Cansaulim", "India"),
    # ("5460", "Diveagar", "India"),
    # ("6939", "Malpe", "India"),
    # ("3691", "Majorda", "India"),
    # ("3231", "Kollur", "India"),
    # ("4227", "Dharmapuri", "India"),
    # ("5095", "Hospet", "India"),
    # ("1997", "Tiruvannamalai", "India"),
    # ("1999", "Maheshwar", "India"),
    # ("2843", "Namchi", "India"),
    # ("4211", "Bekal", "India"),
    # ("6012", "Muttukadu", "India"),
    # ("2839", "Sonamarg", "India"),
    # ("3148", "Omkareshwar", "India"),
    # ("3487", "Subramanya", "India"),
    # ("2736", "Bidar", "India"),
    # ("2131", "Solapur", "India"),
    # ("2575", "Rajahmundry", "India"),
    # ("3630", "Shrivardhan", "India"),
    # ("7929", "Kas", "India"),
    # ("2660", "Chitradurga", "India"),
    # ("4933", "Narkanda", "India"),
    # ("2018", "Cuttack", "India"),
    # ("3396", "Ambaji", "India"),
    # ("2562", "Jhansi", "India"),
    # ("2707", "Sanchi", "India"),
    # ("1970", "Bishnupur", "India"),
    # ("3192", "Munsiyari", "India"),
    # ("3376", "Manipal", "India"),
    # ("6910", "Shingnapur", "India"),
    # ("7184", "Sasan Gir", "India"),
    # ("1759", "Valsad", "India"),
    # ("1690", "Chittoor", "India"),
    # ("1604", "Sirsi", "India"),
    # ("3890", "Pattadakal", "India"),
    # ("2038", "Kolar", "India"),
    # ("2366", "Balasore", "India"),
    # ("7362", "Naukuchiatal", "India"),
    # ("2160", "Amarkantak", "India"),
    # ("3167", "Srikalahasti", "India"),
    # ("1792", "Meerut", "India"),
    # ("1733", "Belgaum", "India"),
    # ("5941", "Modhera", "India"),
    # ("4276", "Kedarnath", "India"),
    # ("2664", "Durgapur", "India"),
    # ("1678", "Sambalpur", "India"),
    # ("1354", "Dindigul", "India"),
    # ("3064", "Puttaparthi", "India"),
    # ("1730", "Gorakhpur", "India"),
    # ("6609", "Dabguli", "India"),
    # ("4524", "Betalbatim", "India"),
    # ("2374", "Mapusa", "India"),
    # ("4652", "Murud", "India"),
    # ("2263", "Theni", "India"),
    # ("4275", "Kotagiri", "India"),
    # ("3304", "Igatpuri", "India"),
    # ("1936", "Pathanamthitta", "India"),
    # ("3115", "Jagdalpur", "India"),
    # ("1781", "Hooghly", "India"),
    # ("1660", "Malappuram", "India"),
    # ("1523", "Secunderabad", "India"),
    # ("146284", "Chinnakanal", "India"),
    # ("3349", "Dhanbad", "India"),
    # ("8980", "Dawki", "India"),
    # ("2365", "Mohali", "India"),
    # ("2976", "Katra", "India"),
    # ("2990", "Sringeri", "India"),
    # ("2123", "Jalpaiguri", "India"),
    # ("1706", "Tumkur", "India"),
    # ("2643", "Ayodhya", "India"),
    # ("8908", "Kannan Devan Hills", "India"),
    # ("4568", "Chakrata", "India"),
    # ("4760", "Manikaran", "India"),
    # ("4318", "Dharmasthala", "India"),
    # ("6149", "Lavasa", "India"),
    # ("146305", "Patnem", "India"),
    # ("7175", "Jwalamukhi", "India"),
    # ("3118", "Purulia", "India"),
    # ("146304", "Palolem", "India"),
    # ("5027", "Sakleshpur", "India"),
    # ("2953", "Nalanda", "India"),
    # ("4340", "Osian", "India"),
    # ("2877", "Chitrakoot", "India"),
    # ("1996", "Tezpur", "India"),
    # ("1793", "Nellore", "India"),
    # ("1139", "Nagapattinam", "India"),
    # ("3900", "Pandharpur", "India"),
    # ("4536", "Cherai Beach", "India"),
    # ("6841", "Ukhimath", "India"),
    # ("7306", "Hunsur", "India"),
    # ("4315", "New Tehri", "India"),
    # ("6969", "Naldehra", "India"),
    # ("2042", "Aizawl", "India"),
    # ("3608", "Virar", "India"),
    # ("2541", "Anantnag", "India"),
    # ("2778", "Bellary", "India"),
    # ("7044", "Hemis", "India"),
    # ("6037", "Pinjore", "India"),
    # ("6746", "Baratang Island", "India"),
    # ("4237", "Chhatarpur", "India"),
    # ("4520", "Dabolim", "India"),
    # ("7159", "Gandikota", "India"),
    # ("6706", "Anjarle", "India"),
    # ("2252", "Uttarkashi", "India"),
    # ("8986", "Salasar", "India"),
    # ("1862", "Ganjam", "India"),
    # ("3299", "Anand", "India"),
    # ("4240", "Sikar", "India"),
    # ("6107", "Nawalgarh", "India"),
    # ("2743", "Gondia", "India"),
    # ("3401", "Nanded", "India"),
    # ("4947", "Gangotri", "India"),
    # ("3150", "Champaner", "India"),
    # ("8350", "Taoru", "India"),
    # ("2046", "Bilaspur", "India"),
    # ("2806", "Sangli", "India"),
    # ("4221", "Bogmalo", "India"),
    # ("4603", "Kalyan", "India"),
    # ("2925", "Courtallam", "India"),
    # ("4181", "Palitana", "India"),
    # ("2596", "Rupnagar", "India"),
    # ("4274", "Ranakpur", "India"),
    # ("2657", "Nalgonda", "India"),
    # ("3405", "Kumbhalgarh", "India"),
    # ("2677", "Adilabad", "India"),
    # ("7272", "Deeg", "India"),
    # ("2811", "Namakkal", "India"),
    # ("2909", "Mehsana", "India"),
    # ("5666", "Kakkabe", "India"),
    # ("5246", "Sanguem", "India"),
    # ("8571", "Channarayapatna", "India"),
    # ("2959", "Mirzapur", "India"),
    # ("7774", "Thirunageswaram", "India"),
    # ("3907", "Thenmala", "India"),
    # ("4300", "Pavagadh", "India"),
    # ("3620", "Kamshet", "India"),
    # ("3590", "Kakinada", "India"),
    # ("4497", "Araku Valley", "India"),
    # ("7200", "Sattal", "India"),
    # ("2828", "Pimpri-Chinchwad", "India"),
    # ("3904", "Agumbe", "India"),
    # ("5043", "Junnar", "India"),
    # ("2867", "Kushinagar", "India"),
    # ("1782", "Bankura", "India"),
    # ("2615", "Gulbarga", "India"),
    # ("2833", "Chalakudy", "India"),
    # ("5562", "Thiruchendur", "India"),
    # ("146319", "Joshimath", "India"),
    # ("3906", "Yuksom", "India"),
    # ("4910", "Mormugao", "India"),
    # ("8994", "Talacauvery", "India"),
    # ("3762", "Karkala", "India"),
    # ("3764", "Bomdila", "India"),
    # ("3629", "Panvel", "India"),
    # ("3636", "Asansol", "India"),
    # ("2373", "Nahan", "India"),
    # ("2617", "Brahmapur", "India"),
    # ("1591", "Jorhat", "India"),
    # ("146268", "Zirakpur", "India"),
    # ("3994", "Tarkarli", "India"),
    # ("5264", "Nuvem", "India"),
    # ("4204", "Mirik", "India"),
    # ("2265", "Erode", "India"),
    # ("4071", "Kundapur", "India"),
    # ("5662", "Bakkhali", "India"),
    # ("9569", "Kaladhungi", "India"),
    # ("2345", "Jowai", "India"),
    # ("6250", "Tarapith", "India"),
    # ("4642", "Channapatna", "India"),
    # ("6196", "Sarahan", "India"),
    # ("4415", "Ramnagar", "India"),
    # ("4569", "Guhagar", "India"),
    # ("2458", "Malda", "India"),
    # ("7430", "Ramnagar", "India"),
    # ("1532", "Amravati", "India"),
    # ("3338", "Panipat", "India"),
    # ("2910", "Guntur", "India"),
    # ("6336", "Sariska", "India"),
    # ("3125", "Bareilly", "India"),
    # ("3748", "Keylong", "India"),
    # ("4852", "Tapovan", "India"),
    # ("6444", "Geyzing", "India"),
    # ("7158", "Yana", "India"),
    # ("2972", "Aritar", "India"),
    # ("5843", "Gudalur", "India"),
    # ("1481", "Sirohi", "India"),
    # ("4896", "Kalady", "India"),
    # ("3371", "Karauli", "India"),
    # ("3619", "Chamarajanagar", "India"),
    # ("4588", "Narmada", "India"),
    # ("4790", "Sonipat", "India"),
    # ("5230", "Lonar", "India"),
    # ("5363", "Kanakapura", "India"),
    # ("6338", "Dahanu", "India"),
    # ("3588", "Karnal", "India"),
    # ("3382", "Vasai", "India"),
    # ("5974", "Ashvem Beach", "India"),
    # ("3082", "Cuddalore", "India"),
    # ("3839", "Pudukkottai", "India"),
    # ("2292", "Ambala", "India"),
    # ("3394", "Kheda", "India"),
    # ("5088", "Nagercoil", "India"),
    # ("6265", "Loutolim", "India"),
    # ("3157", "Cooch Behar", "India"),
    # ("4691", "Yamunotri", "India"),
    # ("5459", "Covelong", "India"),
    # ("6726", "North Paravur", "India"),
    # ("4405", "Bordi", "India"),
    # ("1917", "Jalgaon", "India"),
    # ("2476", "Barmer", "India"),
    # ("5736", "Kodanad", "India"),
    # ("7918", "Dabaspete", "India"),
    # ("4670", "Somvarpet", "India"),
    # ("5525", "Tiruchendur", "India"),
    # ("2271", "Pali", "India"),
    # ("2783", "Durg", "India"),
    # ("5365", "Mantralayam", "India"),
    # ("4998", "Bhadrachalam", "India"),
    # ("2781", "Kurseong", "India"),
    # ("4353", "Rohtak", "India"),
    # ("6277", "Vikarabad", "India"),
    # ("2610", "Jhunjhunu", "India"),
    # ("4271", "Bhilai", "India"),
    # ("5012", "Datia", "India"),
    # ("9099", "Ramgarh", "India"),
    # ("3838", "Dausa", "India"),
    # ("7952", "Someshwar", "India"),
    # ("2662", "Vengurla", "India"),
    # ("8610", "Alchi", "India"),
    # ("3355", "Kolad", "India"),
    # ("3568", "Bokaro Steel City", "India"),
    # ("5627", "Baramati", "India"),
    # ("5850", "Nadia", "India"),
    # ("3373", "Haldwani", "India"),
    # ("3345", "Itanagar", "India"),
    # ("6692", "Tharangambadi", "India"),
    # ("3099", "Aligarh", "India"),
    # ("5020", "Bambolim", "India"),
    # ("2404", "Bilaspur", "India"),
    # ("3763", "Tinsukia", "India"),
    # ("5017", "Devprayag", "India"),
    # ("6182", "Majuli", "India"),
    # ("6442", "Bhojpur", "India"),
    # ("3529", "Thiruvalla", "India"),
    # ("4218", "Bolpur", "India"),
    # ("4604", "Srivilliputhur", "India"),
    # ("7646", "Karnala", "India"),
    # ("2992", "Hosur", "India"),
    # ("3680", "Giridih", "India"),
    # ("6736", "Nalsarovar", "India"),
    # ("8340", "Kufri", "India"),
    # ("6802", "Bapatla", "India"),
    # ("7673", "Hazira", "India"),
    # ("1892", "Thalassery", "India"),
    # ("1947", "Nagaur", "India"),
    # ("3476", "Sibsagar", "India"),
    # ("5019", "Kushalnagar", "India"),
    # ("9457", "Kammasandra", "India"),
    # ("1883", "Tiruppur", "India"),
    # ("2651", "Vidisha", "India"),
    # ("2636", "Anantapur", "India"),
    # ("9547", "Hunder", "India"),
    # ("3353", "Navsari", "India"),
    # ("2599", "Thiruvarur", "India"),
    # ("3067", "Una", "India"),
    # ("3092", "Yellapur", "India"),
    # ("3286", "Kodungallur", "India"),
    # ("2784", "Faizabad", "India"),
    # ("6215", "Chandor", "India"),
    # ("8949", "Thattekad", "India"),
    # ("7331", "Nagarjuna Sagar", "India"),
    # ("2738", "Pathankot", "India"),
    # ("4485", "Nileshwar", "India"),
    # ("4679", "Nelliyampathy", "India"),
    # ("5763", "Karaikal", "India"),
    # ("6528", "Peermade", "India"),
    # ("7416", "Gangolihat", "India"),
    # ("4096", "Talakad", "India"),
    # ("3991", "Chiplun", "India"),
    # ("2128", "Wardha", "India"),
    # ("4590", "Karjat Town", "India"),
    # ("5178", "Jaunpur", "India"),
    # ("7275", "Shegaon", "India"),
    # ("3060", "Mahbubnagar", "India"),
    # ("6273", "Mukutmanipur", "India"),
    # ("6468", "Thariyode", "India"),
    # ("7255", "Diskit", "India"),
    # ("9354", "Temi", "India"),
    # ("2388", "Chanderi", "India"),
    # ("6664", "Tenkasi", "India"),
    # ("3631", "Dimapur", "India"),
    # ("4628", "Buldana", "India"),
    # ("7319", "Salangpur", "India"),
    # ("1985", "Munger", "India"),
    # ("3860", "Panna", "India"),
    # ("6867", "Zuluk", "India"),
    # ("4020", "Hogenakkal", "India"),
    # ("4631", "Chandannagar", "India"),
    # ("8037", "Lamayuru", "India"),
    # ("5209", "Nilambur", "India"),
    # ("1787", "Keonjhar", "India"),
    # ("3661", "Chandrapur", "India"),
    # ("4027", "Burhanpur", "India"),
    # ("4891", "Medak", "India"),
    # ("5765", "Annavaram", "India"),
    # ("9510", "Gingee", "India"),
    # ("2780", "Muzaffarpur", "India"),
    # ("4225", "Tuljapur", "India"),
    # ("1060","Ludhiana","India"),
    #    ('581','Calangute','India'),
    # ('7268','Sadri','India'),
    # ('1664','Fatehpur Sikri','India')
    #  ('2150','Agonda','India'),
    ('1424','Bhavnagar', 'India'),
    ('2083','Howrah','India'),
    ('2264','Rourkela','India'),
    ('2346','Bathinda','India')
]

SERVICE_ACCOUNT_JSON = (
    r"C:\dev\python_runs\scrapy_selenium\quotes-js-project"
    r"\mycasavsc-firebase-adminsdk-u26li-ff3db6bf13.json"
)

OPENAI_MODEL = "gpt-4.1-mini"


# ─── INITIALIZE OPENAI & FIRESTORE ────────────────────────────────────────────
api_key = "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"
if not api_key:
    raise RuntimeError("Missing OPENAI_API_KEY environment variable")

client = OpenAI(api_key=api_key)

if not firebase_admin._apps:
    cred = credentials.Certificate(SERVICE_ACCOUNT_JSON)
    firebase_admin.initialize_app(cred)
db = firestore.client()


# ─── GENERATOR ────────────────────────────────────────────────────────────────
def generate_top_things_to_do(location_context: str) -> dict:
    """
    Returns a JSON object with exactly 12 keys:
      1) "Introduction": 2–3 sentences
      2–11) Ten keys: each begins with an emoji + title, with a 2–3 sentence tip
      12) "Conclusion": 1–2 sentences

    Example location_context: "Agartala, Tripura, India"
    """
    system_msg = "You are a JSON-only generator. Output valid JSON, nothing else."
    user_prompt = f"""
Generate a JSON object with exactly 12 keys.

1) The first key must be "Introduction".
   Its value should be a 2–3 sentence opening paragraph for
   'Top Things To Do in {location_context}', briefly setting the scene and vibe.

2) The next 10 keys should each:
   - Start with one suitable emoji (e.g., "🏰", "🌅", "🍜"),
   - Then a space and a concise title (e.g., "🌅 Sunrise at the Riverfront"),
   - Have a 2–3 sentence paragraph as the value, describing:
       • what the activity or place is,
       • why it is special,
       • and any practical hint (best time, vibe, neighborhood, etc.).
   These should be the top experiences a traveler should not miss in {location_context}.

3) The final key must be "Conclusion".
   Its value should be a 1–2 sentence wrap-up that encourages the traveler and
   summarizes the overall experience of visiting {location_context}.

Do NOT include any other keys, markdown, or code fences."""
    resp = client.chat.completions.create(
        model=OPENAI_MODEL,
        messages=[
            {"role": "system", "content": system_msg},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.0,
        response_format={"type": "json_object"},  # enforce strict JSON
    )

    content = resp.choices[0].message.content.strip()
    try:
        return json.loads(content)
    except JSONDecodeError:
        print(f"⚠️ Failed to parse JSON for {location_context}. Raw response:\n{content}")
        raise


# ─── MAIN WORKFLOW ────────────────────────────────────────────────────────────
def main():
    for doc_id, label, context in DESTINATIONS:
        print(f"\n🛠 Generating 'Top Things To Do' for {context} (doc {doc_id}, label {label})…")

        things = generate_top_things_to_do(context)

        # Store in Firestore under travelInfo/top_things_to_do
        (
            db.collection("allplaces")
              .document(doc_id)
              .collection("travelInfo")
              .document("top_things_to_do")
              .set(things)
        )
        print(f"☁️ Wrote allplaces/{doc_id}/travelInfo/top_things_to_do")

    print("\n✅ All done.")


if __name__ == "__main__":
    main()
